Sai={};Sai.util={};Sai.imagePath=typeof Sai.imagePath!=="undefined"&&Sai.imagePath!==null?Sai.imagePath:"/static/images/sai/";Sai.util.roundToMag=function(n,q){var g;q=typeof q!=="undefined"&&q!==null?q:0;g=Math.pow(10,q);return parseFloat((Math.round(n/g)*g).toFixed(Math.max(0,q)))};Sai.util.round=function(n,q){return parseFloat((Math.round(n/q)*q).toFixed(Math.max(0,Math.ceil(-1*Math.log(q)/Math.LN10))))};
Sai.util.sumArray=function(n){var q,g,a;a=0;q=n.length;for(g=0;0<=q?g<q:g>q;0<=q?g+=1:g-=1)a+=typeof n[g]==="number"?n[g]:0;return a};Sai.util.prettystr=function(n,q){var g;q=typeof q!=="undefined"&&q!==null?q:2;if(typeof n==="number"){if(Math.abs(n)>=1E12){g="t";n/=1E12}else if(Math.abs(n)>=1E9){g="b";n/=1E9}else if(Math.abs(n)>=1E6){g="m";n/=1E6}else if(Math.abs(n)>=1E3){g="k";n/=1E3}else return String(parseFloat(n.toFixed(q)));return parseFloat(n.toFixed(1))+g}return n};
Sai.util.prettynum=function(n){var q;if(!(isNaN(parseFloat(n))||!String(n).match(/^\d+(\.\d+)?$/))){n=String(n).split(".");for(q=/(\d+)(\d{3})/;q.test(n[0]);)n[0]=n[0].replace(q,"$1,$2");return n[0]+(n.length>1?parseFloat("0."+n[1]).toFixed(2).slice(1):"")}};Sai.util.infoSetters=function(n,q){return[function(){return n(q)},function(){return n()}]};
Sai.util.transformCoords=function(n,q){var g;if(q.getScreenCTM){g=q.createSVGPoint();g.x=n.clientX;g.y=n.clientY;g=g.matrixTransform(q.getScreenCTM().inverse());if(navigator.userAgent.toLowerCase().indexOf("chrome")!==-1||navigator.userAgent.toLowerCase().indexOf("safari")!==-1)g.x+=document.body.scrollLeft;return{x:g.x,y:g.y}}else return{x:event.x,y:event.y}};
Sai.util.multiplyColor=function(n,q,g,a){a=typeof a!=="undefined"&&a!==null?a:0;q=a+(1-a)*q;a=Raphael.getRGB(n);if(g){n=a.r+(255-a.r)*(1-q);g=a.g+(255-a.g)*(1-q);q=a.b+(255-a.b)*(1-q)}else{n=a.r*q;g=a.g*q;q=a.b*q}return{r:n,g:g,b:q,str:"rgb("+n+", "+g+", "+q+")"}};
Sai.util.reflectColor=function(n,q){var g,a,b,c,e,f,d,i,j;f=Raphael.getRGB(n);i=Raphael.getRGB(q);j={};a=["r","g","b"];g=0;for(b=a.length;g<b;g++){e=a[g];c=f[e];d=i[e];j[e]=c===d?c:c>d?d*((255-c)/(255-d)):(255*(d-c)+d*c)/d}return"rgb("+j.r+", "+j.g+", "+j.b+")"};Sai.data=typeof Sai.data!=="undefined"&&Sai.data!==null?Sai.data:{};Sai.data.map=typeof Sai.data.map!=="undefined"&&Sai.data.map!==null?Sai.data.map:{};
Raphael.fn.sai=typeof Raphael.fn.sai!=="undefined"&&Raphael.fn.sai!==null?Raphael.fn.sai:{};Raphael.fn.sai.chart=function(n,q,g,a,b,c){b=typeof{line:Sai.LineChart}[b]!=="undefined"&&{line:Sai.LineChart}[b]!==null?{line:Sai.LineChart}[b]:b;b=typeof b!=="undefined"&&b!==null?b:Sai.Chart;return(new b(this,n,q,g,a,c)).render()};(function(){var n,q=Object.prototype.hasOwnProperty;Raphael.fn.sai.prim=typeof Raphael.fn.sai.prim!=="undefined"&&Raphael.fn.sai.prim!==null?Raphael.fn.sai.prim:{};n=function(g,a,b,c){return[function(){g.attr(a);return c?c[0](g):null},function(){g.attr(b);return c?c[1](g):null}]};Raphael.fn.sai.prim.candlestick=function(g,a,b,c,e,f,d,i,j,h,l){d=typeof d!=="undefined"&&d!==null?d:"#000000";f%2||f++;f=this.rect(g-f/2,a,f,b-a||1).attr("stroke",d);c=this.path("M"+g+" "+c+"L"+g+" "+a+"M"+g+" "+b+"L"+g+
" "+e).attr("stroke",d);f.attr("fill",i?d:"#ffffff");d=this.set().push(f,c);if(j){g=n(d,{scale:"1.5,1.5,"+g+","+(a+(b-a)/2),"fill-opacity":0.5},{scale:"1.0,1.0,"+g+","+(a+(b-a)/2),"fill-opacity":1},l);d.hover(g[0],g[1])}return d};Raphael.fn.sai.prim.line=function(g,a,b){var c,e,f,d;a=typeof a!=="undefined"&&a!==null?a:"#000000";b=typeof b!=="undefined"&&b!==null?b:1;c=0;for(e=g.length;c<e;c++){f=g[c];if(typeof f!=="undefined"&&f!==null)if(typeof d!=="undefined"&&d!==null)d+="L"+f[0]+" "+f[1];else d=
"M"+f[0]+" "+f[1]}return this.path(d).attr({stroke:a,"stroke-width":b})};Raphael.fn.sai.prim.area=function(g,a,b,c){var e,f,d,i,j;if(g.length<2)return this.set();a=typeof a!=="undefined"&&a!==null?a:"#000000";b=typeof b!=="undefined"&&b!==null?b:1;e=0;for(f=g.length;e<f;e++){i=g[e];if(typeof i!=="undefined"&&i!==null)if(typeof j!=="undefined"&&j!==null){j+="L"+i[0]+" "+i[1];d+="L"+i[0]+" "+i[1]}else{j="M"+i[0]+" "+i[1];d="M"+i[0]+" "+i[1]}}for(g=c.length-1;c.length-1<=0?g<=0:g>=0;g+=-1)d+="L"+c[g][0]+
","+c[g][1];c=this.path(d).attr({fill:a,"stroke-width":0,"stroke-opacity":0,"fill-opacity":0.35});a=this.path(j).attr({stroke:a,"stroke-width":b});return this.set().push(c,a)};Raphael.fn.sai.prim.stackedBar=function(g,a,b,c,e,f,d){var i,j,h,l,k,o,m,p;if(e&&typeof(i=g[g.length-1])!=="undefined"&&i!==null)p=c-g[g.length-1][1];b*=0.67;m=this.set();l=c;j=g.length;for(i=0;0<=j?i<j:i>j;0<=j?i+=1:i-=1){o=i;if(typeof(h=g[o])!=="undefined"&&h!==null&&g[o][1]!==c){k=l-g[o][1];l=o===0?1:0;m.push(l=this.rect(g[o][0]-
b/2,g[o][1],b,k-l).attr("fill",(a==undefined?undefined:a[o])||"#000000").attr("stroke",(a==undefined?undefined:a[o])||"#000000"));if(e){k=n(l,{"fill-opacity":"0.75"},{"fill-opacity":"1.0"},[function(r){return function(){d[0]&&d[0]();return f({"(selected)":Sai.util.prettystr(r)+"%"},false)}}(100*k/p),d[1]]);l.hover(k[0],k[1])}l=g[o][1]}}return m};Raphael.fn.sai.prim.groupedBar=function(g,a,b,c,e,f,d){var i,j,h,l;f=this.set();j=b/(g.length+1);l=(b-j)/2;b=g.length;for(h=0;0<=b?h<b:h>b;0<=b?h+=1:h-=1)if(typeof(i=
g[h]==undefined?undefined:g[h][0])!=="undefined"&&i!==null)f.push(this.rect(g[h][0]-l+h*j,g[h][1],j-1,c-g[h][1]-0.5).attr("fill",(a==undefined?undefined:a[h])||"#000000").attr("stroke",(a==undefined?undefined:a[h])||"#000000"));if(e){g=n(f,{"fill-opacity":"0.75"},{"fill-opacity":"1.0"},d);f.hover(g[0],g[1])}return f};Raphael.fn.sai.prim.haxis=function(g,a,b,c,e,f,d){var i,j,h,l,k,o,m,p,r,u,v,s;d=typeof d!=="undefined"&&d!==null?d:[10,5];e=typeof e!=="undefined"&&e!==null?e:1;f=typeof f!=="undefined"&&
f!==null?f:"#000000";h=this.path("M"+a+" "+b+"l"+c+" 0").attr("stroke",f);u=this.set();j=this.set();p=c/12;p=p<g.length?Math.ceil(g.length/p):1;o=c/(g.length-1)*p;s=a;v=-1;r=false;c=0;i=g.length;for(m=0;0<=i?m<i:m>i;m+=p){l=g[m];if(typeof l!=="undefined"&&l!==null){k=d[String(l)?0:1];u.push(this.path("M"+s+" "+b+"l0 "+k).attr("stroke",f));if(l!==""){k=this.text(s,b+k+2,Sai.util.prettystr(l));l=k.getBBox();k.attr("y",k.attr("y")+l.height/2);j.push(k);k=l.width;c=Math.max(k,c);if(l.x<=v)r=true;if(l.x+
k>v)v=l.x+k}}s+=o}g=this.set().push(h,u,j);if(r){f=j.items;j=0;for(h=f.length;j<h;j++){k=f[j];k.rotate(-90);k.translate(0,k.getBBox().width/2-2)}g.push(this.rect(a,b,1,e+c+d[0]).attr("opacity","0"))}return g};Raphael.fn.sai.prim.vaxis=function(g,a,b,c,e,f,d,i){var j,h,l,k,o,m;i=typeof i!=="undefined"&&i!==null?i:[10,5];d=typeof d!=="undefined"&&d!==null?d:"#000000";f=typeof f!=="undefined"&&f!==null?f:false;l=this.path("M"+a+" "+b+"l0 "+-c).attr("stroke",d);k=this.set();e=this.set();c=c/(g.length-
1);m=b;b=0;for(j=g.length;b<j;b++){o=g[b];if(o!==null){h=i[String(o)?0:1];k.push(this.path("M"+a+" "+m+"l"+(f?h:-h)+" 0").attr("stroke",d));h=this.text(a+(f?1:-1)*(h+2),m,Sai.util.prettystr(o));h.attr({x:h.attr("x")+(f?1:-1)*h.getBBox().width/2,fill:d});e.push(h)}m-=c}return this.set().push(l,k,e)};Raphael.fn.sai.prim.popup=function(g,a,b){var c,e,f,d,i,j;this.set();j=this.set();e=0;f=a+5+5;if("__HEAD__"in b){c=this.text(g,f,b.__HEAD__).attr({fill:"#cfc","font-size":"12","font-weight":"bold"});e=
Math.max(e,c.getBBox().width);j.push(c);f+=17}for(i in b)if(q.call(b,i))if(i!=="__HEAD__"){d=this.text(g+5,f,i+" = "+b[i]).attr({fill:"white","font-weight":"bold"});d.translate(d.getBBox().width/2,0);e=Math.max(e,d.getBBox().width);f+=10;j.push(d)}b=e+10;this.rect(g,a,b,f-a,5).attr({fill:"black","fill-opacity":".85",stroke:"black"});typeof c==="undefined"||c==undefined||c.translate(b/2);return j.toFront()};Raphael.fn.sai.prim.legend=function(g,a,b,c,e){var f,d,i,j,h,l,k,o,m;a-=14;k=this.set();h=g;
l=a;for(m in c)if(q.call(c,m)){o=this.text(h+14,l,m).attr({fill:typeof(f=e==undefined?undefined:e[m])!=="undefined"&&f!==null?e==undefined?undefined:e[m]:"black"});o.translate(o.getBBox().width/2,o.getBBox().height/2);j=this.rect(h,l,9,9).attr({fill:typeof(d=c[m])!=="undefined"&&d!==null?c[m]:"black",stroke:typeof(i=e==undefined?undefined:e[m])!=="undefined"&&i!==null?e==undefined?undefined:e[m]:"black"});j=this.set().push(o,j);if(h-g+15+j.getBBox().width>b){k.translate(0,-14);j.translate(g-h,a-l);
h=g;l=a}h+=j.getBBox().width+15;k.push(j)}return k};Raphael.fn.sai.prim.info=function(g,a,b,c){var e,f,d,i,j,h;i=this.set();d=g;a=a;for(f in c)if(q.call(c,f))if(c[f]!==null){j=this.text(d,a,f+(f===""?"":": ")+(typeof(e=Sai.util.prettynum(c[f]))!=="undefined"&&e!==null?Sai.util.prettynum(c[f]):Sai.util.prettystr(c[f])));h=j.getBBox();j.translate(h.width/2,h.height/2);if(d-g+15+h.width>b){j.translate(g-d,14);d=g;a+=14}d+=h.width+15;i.push(j)}return i};Raphael.fn.sai.prim.hoverShape=function(g,a,b,c){g=
g(this).attr(a);b=n(g,c&&c[0]||{},c&&c[1]||{},b);g.mouseover(b[0]);g.mouseout(b[1]);return g};Raphael.fn.sai.prim.histogram=function(g,a,b,c,e,f,d,i,j,h,l,k){var o,m,p,r;h=typeof h!=="undefined"&&h!==null?h:"#ffffff";k=typeof k!=="undefined"&&k!==null?k:10;r=this.set();r.push(this.rect(g,a-c,b,c).attr({"stroke-width":0,"stroke-opacity":0,fill:h}));c=a-(c-12);a-=5;f=typeof f!=="undefined"&&f!==null?f:0;d=typeof d!=="undefined"&&d!==null?d:1;r.push(f=this.text(g,a,Sai.util.prettystr(f)));f.translate(f.getBBox().width/
2,0);r.push(d=this.text(g+b,a,Sai.util.prettystr(d)));d.translate(-d.getBBox().width/2,0);a-=7;d={};h=f=0;for(o=e.length;h<o;h++){p=e[h];p=Math.min(k-1,Math.floor(k*p/1));if(p in d)d[p]+=1;else d[p]=1;f=Math.max(f,d[p])}r.push(this.path("M"+g+","+a+" l"+b+", 0").attr("stroke",j));a-=1;h=b/k;for(m in d)if(q.call(d,m)){e=(a-c)*(d[m]/f);r.push(this.rect(g+(parseInt(m)+0.2)*h,a-e,h*0.6,e).attr({fill:Sai.util.multiplyColor(j,(parseInt(m)+0.5)/k,l,0.2).str,"stroke-width":l?0.35:0,"stroke-opacity":l?1:0,
stroke:"#000000"}))}r.push(this.text(g+b/2,c-6,Sai.util.prettystr(i)));return r}})();(function(){var n=Object.prototype.hasOwnProperty,q=function(g,a){var b=function(){};b.prototype=a.prototype;g.prototype=new b;g.prototype.constructor=g;typeof a.extended==="function"&&a.extended(g);g.__superClass__=a.prototype};Sai.Plot=function(g,a,b,c,e,f,d,i){this.opts=i;this.rawdata=d;this.data=f;this.h=e;this.w=c;this.y=b;this.x=a;this.r=g;this.opts=typeof this.opts!=="undefined"&&this.opts!==null?this.opts:{};this.setDenormalizedData();this.set=this.r.set();return this};Sai.Plot.prototype.setDenormalizedData=
function(){var g,a,b,c,e,f,d,i,j,h;if(this.data instanceof Array){g=[];b=this.data;a=0;for(c=b.length;a<c;a++){j=b[a];g.push(this.denormalize(j))}return this.dndata=g}else{this.dndata=typeof this.dndata!=="undefined"&&this.dndata!==null?this.dndata:{};g=[];a=this.data;for(h in a)if(n.call(a,h))g.push(this.dndata[h]=function(){e=[];d=this.data[h];f=0;for(i=d.length;f<i;f++){j=d[f];e.push(this.denormalize(j))}return e}.call(this));return g}};Sai.Plot.prototype.denormalize=function(g){if(g instanceof
Array)return[this.x+this.w*g[0],this.y-this.h*g[1]]};Sai.Plot.prototype.render=function(){this.set.push(this.r.rect(20,20,20,20).attr("fill","red"),this.r.circle(40,40,10).attr("fill","blue"));return this};Sai.LinePlot=function(){return Sai.Plot.apply(this,arguments)};q(Sai.LinePlot,Sai.Plot);Sai.LinePlot.prototype.setDenormalizedData=function(){var g,a,b;Sai.LinePlot.__superClass__.setDenormalizedData.apply(this,arguments);g=[];a=this.dndata;for(b in a)if(n.call(a,b))g.push(this.dndata[b].length===
1&&(this.dndata[b]==undefined?undefined:this.dndata[b][0]==undefined?undefined:this.dndata[b][0][0])===this.x?this.dndata[b].push([this.x+this.w,this.dndata[b][0][1]]):null);return g};Sai.LinePlot.prototype.render=function(g,a){var b,c;this.set.remove();b=this.dndata;for(c in b)if(n.call(b,c))c.match("^__")||this.set.push(this.r.sai.prim.line(this.dndata[c],(g==undefined?undefined:g[c])||"black",a||1));return this};Sai.AreaPlot=function(){return Sai.LinePlot.apply(this,arguments)};q(Sai.AreaPlot,
Sai.LinePlot);Sai.AreaPlot.prototype.render=function(g,a,b){var c,e,f,d,i,j,h;this.set.remove();c=this.dndata;for(h in c)if(n.call(c,h))if(!h.match("^__")){e=typeof e!=="undefined"&&e!==null?e:[this.denormalize([0,0]),this.denormalize([1,0])];this.set.push(this.r.sai.prim.area(this.dndata[h],(g==undefined?undefined:g[h])||"black",a||1,e));if(b){e=[];d=this.dndata[h];f=0;for(i=d.length;f<i;f++){j=d[f];e.push([j[0],j[1]-a/2])}e=e}}return this};Sai.CandlestickPlot=function(){return Sai.Plot.apply(this,
arguments)};q(Sai.CandlestickPlot,Sai.Plot);Sai.CandlestickPlot.prototype.render=function(g,a,b,c){var e,f,d,i,j,h,l,k,o;this.set.remove();j=(g==undefined?undefined:g.up)||"black";i=(g==undefined?undefined:g.down)||"red";a=typeof a!=="undefined"&&a!==null?a:5;g=this.dndata.open.length;for(h=0;0<=g?h<g:h>g;0<=g?h+=1:h-=1)if(typeof(e=this.dndata.close[h])!=="undefined"&&e!==null){o=this.dndata.close[h][1]<this.dndata.open[h][1];l={};f=this.rawdata;for(k in f)if(n.call(f,k))l[k]=this.rawdata[k][h];this.set.push(this.r.sai.prim.candlestick(this.dndata.open[h][0],
o&&this.dndata.close[h][1]||this.dndata.open[h][1],o&&this.dndata.open[h][1]||this.dndata.close[h][1],this.dndata.high[h][1],this.dndata.low[h][1],a||5,h&&typeof(d=this.dndata.close[h-1])!=="undefined"&&d!==null&&this.dndata.close[h-1][1]<this.dndata.close[h][1]?i:j,!o,b,c,Sai.util.infoSetters(c,l)))}return this};Sai.BarPlot=function(){return Sai.Plot.apply(this,arguments)};q(Sai.BarPlot,Sai.Plot);Sai.BarPlot.prototype.render=function(g,a,b,c){var e,f,d,i,j,h,l;this.set.remove();j=0;d=[];g=g?this.r.sai.prim.stackedBar:
this.r.sai.prim.groupedBar;e=this.dndata;for(l in e)if(n.call(e,l)){j=this.dndata[l].length;d.push((a==undefined?undefined:a[l])||"black")}for(e=0;0<=j?e<j:e>j;0<=j?e+=1:e-=1){a=[];f=this.dndata;for(l in f)n.call(f,l)&&a.push(this.dndata[l][e]);i={};f=this.rawdata;for(h in f)if(n.call(f,h))i[h]=this.rawdata[h][e];this.set.push(g(a,d,this.w/j,this.y,b,c,Sai.util.infoSetters(c,i)))}return this};Sai.GeoPlot=function(){return Sai.Plot.apply(this,arguments)};q(Sai.GeoPlot,Sai.Plot);Sai.GeoPlot.prototype.getRegionColor=
function(g,a,b){return Sai.util.multiplyColor(g[b],(this.data[b][a]==undefined?undefined:this.data[b][a][1])||0,this.opts.fromWhite,this.opts.fromWhite?0.2:0).str};Sai.GeoPlot.prototype.getRegionOpacity=function(g,a){var b;return typeof(b=this.data[a][g]==undefined?undefined:this.data[a][g][1])!=="undefined"&&b!==null?1:this.opts.fromWhite?0.15:0.25};Sai.GeoPlot.prototype.render=function(g,a,b,c,e,f,d){var i,j,h,l,k;this.set.remove();l=this.rawdata[b];k={};i=l.length;for(h=0;0<=i?h<i:h>i;0<=i?h+=
1:h-=1)k[l[h]]=h;i=a.paths;for(j in i)n.call(i,j)&&function(){var o,m,p,r,u,v=j;u=k[v];p=a.name[v];p={region:typeof p!=="undefined"&&p!==null?p:v};o=this.rawdata;for(m in o)if(n.call(o,m))if(m!==b)p[m]=this.rawdata[m][u];m=this.getRegionColor(g,u,c);u=this.getRegionOpacity(u,c);r=Sai.util.infoSetters(d,p);return this.set.push(this.r.sai.prim.hoverShape(function(s,w,t,z){return function(y){return y.path(s).translate(t,z).scale(w,w,t,z)}}(a.paths[v],Math.min(this.w/a.width,this.h/a.height),this.x,this.y-
this.h),{fill:m,stroke:this.opts.fromWhite?"black":e,"stroke-width":0.5,opacity:u},f?[function(s){navigator.userAgent.toLowerCase().indexOf("msie")!==-1||navigator.userAgent.toLowerCase().indexOf("opera")!==-1||s.toFront();return r[0]()},r[1]]:null,f?[{"fill-opacity":0.75,"stroke-width":this.opts.fromWhite?2:0.5},{"fill-opacity":1,"stroke-width":0.5}]:null))}.call(this);i=this.set.getBBox();this.set.translate((this.w-i.width)/2,(this.h-i.height)/2);return this};Sai.ChromaticGeoPlot=function(){return Sai.GeoPlot.apply(this,
arguments)};q(Sai.ChromaticGeoPlot,Sai.GeoPlot);Sai.ChromaticGeoPlot.prototype.getRegionColor=function(g,a){var b,c,e,f,d,i;f=e=c=0;b=this.data;for(i in b)if(n.call(b,i)){d=Sai.util.multiplyColor(g[i],(this.data[i][a]==undefined?undefined:this.data[i][a][1])||0,this.opts.fromWhite);f+=d.r;e+=d.g;c+=d.b}return"rgb("+f+", "+e+", "+c+")"};Sai.ChromaticGeoPlot.prototype.getRegionOpacity=function(g){var a,b,c;a=this.data;for(c in a)if(n.call(a,c))if(typeof(b=this.data[c][g]==undefined?undefined:this.data[c][g][1])!==
"undefined"&&b!==null)return 1;return 0.25}})();(function(){var n=Object.prototype.hasOwnProperty,q=function(a,b){return function(){return a.apply(b,arguments)}},g=function(a,b){var c=function(){};c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;typeof b.extended==="function"&&b.extended(a);a.__superClass__=b.prototype};Sai.Chart=function(a,b,c,e,f,d,i,j){var h;this.opts=j;this.__LABELS__=i;this.h=f;this.w=e;this.y=c;this.x=b;this.r=a;h=this;this.drawInfo=function(){return Sai.Chart.prototype.drawInfo.apply(h,arguments)};this.getStackedMax=
function(){return Sai.Chart.prototype.getStackedMax.apply(h,arguments)};this.setData=function(){return Sai.Chart.prototype.setData.apply(h,arguments)};this.opts=typeof this.opts!=="undefined"&&this.opts!==null?this.opts:{};this.opts.bgcolor=typeof this.opts.bgcolor!=="undefined"&&this.opts.bgcolor!==null?this.opts.bgcolor:"white";this.setData(d);this.padding={left:5,right:5,top:5,bottom:5};return this};Sai.Chart.prototype.groupsToNullPad=function(){return[]};Sai.Chart.prototype.nonNegativeGroups=
function(){return[]};Sai.Chart.prototype.setData=function(a){var b,c,e,f,d,i,j,h,l,k,o,m;this.data={};for(m in a)if(n.call(a,m)){i=this.data;j=m;if(a[m]instanceof Array){b=[];e=a[m];c=0;for(f=e.length;c<f;c++){l=e[c];b.push(typeof l==="string"&&l.match(/^\d+(\.\d+)?$/)&&!isNaN(d=parseFloat(l))?d:l)}b=b}else b=a[m];i[j]=b}a=this.dataGroups(a);o=this.nonNegativeGroups();for(k in a)if(n.call(a,k))if(a[k].length>0)if(function(){for(var p=0,r=o.length;p<r;p++)if(o[p]===k)return true;return false}.call(this)){i=
a[k];d=0;for(j=i.length;d<j;d++){m=i[d];if(typeof(h=this.data[m])!=="undefined"&&h!==null){b=this.data[m].length;for(c=0;0<=b?c<b:c>b;0<=b?c+=1:c-=1)if(this.data[m][c]<0)this.data[m][c]*=-1}}}d=this.groupsToNullPad();h=0;for(i=d.length;h<i;h++){k=d[h];if(k in a){b=a[k];j=0;for(c=b.length;j<c;j++){m=b[j];this.nullPad(m)}}}return this.normalize(this.data)};Sai.Chart.prototype.nullPad=function(a){return a in this.data?this.data[a]=[null].concat(this.data[a].concat([null])):null};Sai.Chart.prototype.caresAbout=
function(a){return!(a.match("^__")||a===this.__LABELS__)};Sai.Chart.prototype.dataGroups=function(a){var b,c,e;b=[];for(e in a)n.call(a,e)&&this.caresAbout(e)&&b.push(e);c=[];for(e in a)if(n.call(a,e))if(e.match("^__")||e===this.__LABELS__)c.push(e);return{all:b,__META__:c}};Sai.Chart.prototype.getYAxisVals=function(a,b,c){var e,f,d;if(a===b)return[0,b,b*2];c=typeof c!=="undefined"&&c!==null?c:false;for(e=1;(b-a)*e<10;)e*=10;a*=e;b*=e;d=Math.floor(f=Math.log(b-a)/Math.LN10-0.4);d=Math.pow(10,d);if(f%
1>0.7&&!c)d*=4;else if(f%1>0.35&&!c)d*=2;f=Sai.util.round(a-(c?d/2.1:d/1.9),d);if(f<=0&&0<=a)f=0;a=Sai.util.round(b+(c?d/2.1:d/1.9),d);f/=e;a/=e;d/=e;e=[];for(b=f;f<=a?b<=a:b>=a;b+=d)e.push(Sai.util.round(b,d));return e};Sai.Chart.prototype.getMax=function(a,b){var c,e,f,d,i,j,h,l,k,o;return Math.max.apply(Math,function(){c=[];e=0;for(f=b.length;e<f;e++){o=b[e];if(typeof(l=a[o])!=="undefined"&&l!==null)c.push(Math.max.apply(Math,function(){d=[];j=a[o];i=0;for(h=j.length;i<h;i++){k=j[i];typeof k!==
"undefined"&&k!==null&&typeof k==="number"&&d.push(k)}return d}()))}return c}())};Sai.Chart.prototype.getMin=function(a,b){var c,e,f,d,i,j,h,l,k,o;return Math.min.apply(Math,function(){c=[];e=0;for(f=b.length;e<f;e++){o=b[e];if(typeof(l=a[o])!=="undefined"&&l!==null)c.push(Math.min.apply(Math,function(){d=[];j=a[o];i=0;for(h=j.length;i<h;i++){k=j[i];typeof k!=="undefined"&&k!==null&&typeof k==="number"&&d.push(k)}return d}()))}return c}())};Sai.Chart.prototype.getStackedMax=function(a,b){var c,e,
f,d,i,j,h;return Math.max.apply(Math,function(){c=[];e=a[this.__LABELS__].length;for(j=0;0<=e?j<e:j>e;0<=e?j+=1:j-=1)c.push(Sai.util.sumArray(function(){f=[];d=0;for(i=b.length;d<i;d++){h=b[d];h!==this.__LABELS__&&f.push(a[h][j])}return f}.call(this)));return c}.call(this))};Sai.Chart.prototype.getStackedMin=function(){return 0};Sai.Chart.prototype.normalize=function(a){var b,c,e,f,d,i,j,h,l,k,o,m,p,r,u,v,s,w,t,z,y,B,x,A;w=this.dataGroups(a);this.ndata={};if(typeof(b=this.opts.stacked)!=="undefined"&&
b!==null)this.stackedNdata={};b=function(D,C,E){if(typeof D==="number")return C===E?1:(D-C)/(E-C);return null};for(s in w)if(n.call(w,s))if(!(s.match("^__")||Sai.util.sumArray(function(){c=[];f=w[s];e=0;for(d=f.length;e<d;e++){x=f[e];c.push(this.data[x].length)}return c}.call(this))===0)){this.ndata[s]={};if(typeof(i=this.opts.stacked)!=="undefined"&&i!==null){this.stackedNdata[s]={};v={}}y=this.opts.stacked?this.getStackedMin:this.getMin;j=this.opts.stacked?this.getStackedMax:this.getMax;y=y(a,w[s]);
z=j(a,w[s]);A=this.getYAxisVals(y,z);y=A[0];z=A[A.length-1];h=w[s];j=0;for(l=h.length;j<l;j++){x=h[j];if(typeof(k=a[x])!=="undefined"&&k!==null){var F=this.ndata[s],G=x;o=[];m=a[x].length;for(t=0;0<=m?t<m:t>m;0<=m?t+=1:t-=1)o.push(typeof(p=a[x][t])!=="undefined"&&p!==null&&(B=b(a[x][t],y,z))!==null?[t/(a[x].length-1||1),B]:null);F[G]=o;if(typeof(u=this.opts.stacked)!=="undefined"&&u!==null){this.stackedNdata[s][x]=[];o=a[x].length;for(t=0;0<=o?t<o:t>o;0<=o?t+=1:t-=1){m=v[t]||0;m=[t/(a[x].length-1||
1),typeof(r=a[x][t])!=="undefined"&&r!==null&&(B=b(a[x][t],y,z))!==null?B+m:m];this.stackedNdata[s][x].push(m);if(m!==null)v[t]=m[1]}}this.ndata[s].__YVALS__=A}}}return[]};Sai.Chart.prototype.addAxes=function(a,b){var c,e,f,d,i,j,h,l,k,o,m,p;this.axisWidth=1.5;this.padding.top+=5;for(p=this.data[this.__LABELS__].length-1;this.data[this.__LABELS__].length-1<=0?p<=0:p>=0;this.data[this.__LABELS__].length-1<=0?p+=1:p-=1)if(typeof(c=this.data[this.__LABELS__][p])!=="undefined"&&c!==null){c=this.r.text(0,
0,Sai.util.prettystr(this.data[this.__LABELS__][p]));this.padding.right+=c.getBBox().width/2;c.remove();break}c=this.h-(this.padding.bottom+this.padding.top);if(typeof(f=this.ndata[a])!=="undefined"&&f!==null){f=this.r.sai.prim.vaxis(typeof(e=this.ndata[a]==undefined?undefined:this.ndata[a].__YVALS__)!=="undefined"&&e!==null?this.ndata[a]==undefined?undefined:this.ndata[a].__YVALS__:[0,"?"],this.x+this.padding.left,this.y-this.padding.bottom,c,this.axisWidth);e=f.getBBox().width;f.remove()}else e=
0;if(typeof(i=this.ndata[b])!=="undefined"&&i!==null){f=this.r.sai.prim.vaxis(typeof(d=this.ndata[b]==undefined?undefined:this.ndata[b].__YVALS__)!=="undefined"&&d!==null?this.ndata[b]==undefined?undefined:this.ndata[b].__YVALS__:[0,"?"],this.x+this.padding.left,this.y-this.padding.bottom,c,this.axisWidth);d=f.getBBox().width;f.remove()}else d=0;this.haxis=this.r.sai.prim.haxis(this.data[this.__LABELS__],this.x+this.padding.left+e,this.y-this.padding.bottom,this.w-this.padding.left-this.padding.right-
e-d,this.axisWidth);d=this.haxis.getBBox().height;if(isNaN(d))d=1;this.haxis.translate(0,-d);this.padding.bottom+=d;c=this.h-(this.padding.bottom+this.padding.top);if(typeof(h=this.ndata[a])!=="undefined"&&h!==null){this.vaxis=this.r.sai.prim.vaxis(typeof(j=this.ndata[a]==undefined?undefined:this.ndata[a].__YVALS__)!=="undefined"&&j!==null?this.ndata[a]==undefined?undefined:this.ndata[a].__YVALS__:[0,"?"],this.x+this.padding.left,this.y-this.padding.bottom,c,this.axisWidth);this.vaxis.translate(this.vaxis.getBBox().width,
0);this.padding.left+=this.vaxis.getBBox().width}if(typeof(m=this.ndata[b])!=="undefined"&&m!==null){this.vaxis_right=this.r.sai.prim.vaxis(typeof(l=this.ndata[b]==undefined?undefined:this.ndata[b].__YVALS__)!=="undefined"&&l!==null?this.ndata[b]==undefined?undefined:this.ndata[b].__YVALS__:[0,"?"],this.w-this.padding.right,this.y-this.padding.bottom,c,this.axisWidth,true,typeof(k=this.ndata[a])!=="undefined"&&k!==null?typeof(o=this.colors.__RIGHTAXIS__)!=="undefined"&&o!==null?this.colors.__RIGHTAXIS__:
"blue":"black");this.vaxis_right.translate(-this.vaxis_right.getBBox().width,0);this.padding.right+=this.vaxis_right.getBBox().width}this.setPlotCoords();return this.r.set().push(this.haxis).push(this.vaxis)};Sai.Chart.prototype.setPlotCoords=function(){this.px=this.x+this.padding.left;this.py=this.y-this.padding.bottom;this.pw=this.w-this.padding.left-this.padding.right;return this.ph=this.h-this.padding.bottom-this.padding.top};Sai.Chart.prototype.drawBG=function(){var a,b,c,e;return this.bg=this.r.rect(typeof(a=
this.px)!=="undefined"&&a!==null&&this.px||this.x,typeof(b=this.py)!=="undefined"&&b!==null&&this.py-this.ph||this.y-this.h,typeof(c=this.pw)!=="undefined"&&c!==null&&this.pw||this.w,typeof(e=this.ph)!=="undefined"&&e!==null&&this.ph||this.h).attr({fill:this.opts.bgcolor,"stroke-width":0,"stroke-opacity":0}).toBack()};Sai.Chart.prototype.logoPos=function(){var a,b,c,e,f;f=typeof(a=this.px)!=="undefined"&&a!==null&&typeof(b=this.pw)!=="undefined"&&b!==null?this.px+this.pw-160-5:this.w+this.x-160-this.padding.right;
a=typeof(c=this.py)!=="undefined"&&c!==null&&typeof(e=this.ph)!=="undefined"&&e!==null?this.py-this.ph+5:this.y-this.h+this.padding.top;return[f,a,160,34]};Sai.Chart.prototype.drawLogo=function(){var a;a=this.logoPos();return this.logo=this.r.image(Sai.imagePath+"logo.png",a[0],a[1],a[2],a[3]).attr({opacity:0.25})};Sai.Chart.prototype.render=function(){this.plot=typeof this.plot!=="undefined"&&this.plot!==null?this.plot:new Sai.Plot(this.r);this.plot.render();return this};Sai.Chart.prototype.showError=
function(a){return this.r.text(this.x+this.w/2,this.y-this.h/2,a)};Sai.Chart.prototype.setColors=function(a){var b;this.colors=typeof this.colors!=="undefined"&&this.colors!==null?this.colors:{};for(b in a)if(n.call(a,b))if(b in this.data)this.colors[b]=a[b];return this};Sai.Chart.prototype.setColor=function(a,b){this.colors=typeof this.colors!=="undefined"&&this.colors!==null?this.colors:{};this.colors[a]=b;return this};Sai.Chart.prototype.drawGuideline=function(a,b){var c;b=typeof b!=="undefined"&&
b!==null?b:"all";if(!(typeof(c=this.ndata[b]==undefined?undefined:this.ndata[b].__YVALS__)!=="undefined"&&c!==null))return null;c=this.ndata[b].__YVALS__[0];if(!(a>c))return null;c=(a-c)/(this.ndata[b].__YVALS__[this.ndata[b].__YVALS__.length-1]-c);this.guidelines=typeof this.guidelines!=="undefined"&&this.guidelines!==null?this.guidelines:this.r.set();c=new Sai.LinePlot(this.r,this.px,this.py,this.pw,this.ph,{guideline:[[0,c],[1,c]]});c.render({guideline:"#ccc"});return this.guidelines.push(c.set)};
Sai.Chart.prototype.drawLegend=function(a){var b,c,e,f,d,i,j,h;if(a=typeof a!=="undefined"&&a!==null?a:this.colors){e={};j={};b=a;for(h in b)if(n.call(b,h))if(h!==this.__LABELS__){e[h]=a[h];j[h]="black";if(typeof(i=this.opts.groups==undefined?undefined:this.opts.groups.right)!=="undefined"&&i!==null)if(function(){for(var l=0,k=(d=this.opts.groups.right).length;l<k;l++)if(d[l]===h)return true;return false}.call(this))j[h]=typeof(c=this.ndata.left)!=="undefined"&&c!==null?typeof(f=this.colors.__RIGHTAXIS__)!==
"undefined"&&f!==null?this.colors.__RIGHTAXIS__:"blue":"black"}this.legend=this.r.sai.prim.legend(this.x,this.y-this.padding.bottom,this.w,e,j);if(this.legend.length>0)this.padding.bottom+=this.legend.getBBox().height+15;return this.legend.translate((this.w-this.legend.getBBox().width)/2,0)}};Sai.Chart.prototype.drawTitle=function(){var a;if(typeof(a=this.opts.title)!=="undefined"&&a!==null){this.title=this.r.text(this.x+this.w/2,this.y-this.h,this.opts.title).attr({"font-size":20});this.title.translate(0,
this.title.getBBox().height/2);return this.padding.top+=this.title.getBBox().height+5}};Sai.Chart.prototype.setupInfoSpace=function(){this.info_y=this.y-this.h+this.padding.top;this.info_x=this.x+this.padding.left;this.info_w=this.w-this.padding.left-this.padding.right;return this.padding.top+=30};Sai.Chart.prototype.drawInfo=function(a,b){var c,e,f;b=typeof b!=="undefined"&&b!==null?b:true;a=typeof a!=="undefined"&&a!==null?a:typeof(c=this.default_info)!=="undefined"&&c!==null?this.default_info():
{};if(b)this.info_data={};this.info&&this.info.remove();c=a;for(f in c)if(n.call(c,f))f.match("^__")||(this.info_data[f]=typeof(e=a[f])!=="undefined"&&e!==null?a[f]:"(no data)");return this.info=this.r.sai.prim.info(this.info_x,this.info_y,this.info_w,this.info_data)};Sai.Chart.prototype.getIndex=function(a){a=Sai.util.transformCoords(a,this.r.canvas).x;return Math.round((this.data[this.__LABELS__].length-1)*(a-this.px)/this.pw)};Sai.LineChart=function(){return Sai.Chart.apply(this,arguments)};g(Sai.LineChart,
Sai.Chart);Sai.LineChart.prototype.nonNegativeGroups=function(){return this.opts.stacked?["all","left","right"]:[]};Sai.LineChart.prototype.dataGroups=function(){var a,b,c,e,f,d;d=Sai.LineChart.__superClass__.dataGroups.apply(this,arguments);if(typeof(f=this.opts.groups==undefined?undefined:this.opts.groups.left)!=="undefined"&&f!==null&&typeof(a=this.opts.groups==undefined?undefined:this.opts.groups.right)!=="undefined"&&a!==null){a=[];c=this.opts.groups.left;b=0;for(e=c.length;b<e;b++){f=c[b];this.caresAbout(f)&&
f in this.data&&a.push(f)}d.left=a;a=[];c=this.opts.groups.right;b=0;for(e=c.length;b<e;b++){f=c[b];this.caresAbout(f)&&f in this.data&&a.push(f)}d.right=a}return d};Sai.LineChart.prototype.render=function(){var a,b,c,e,f,d,i,j;this.drawTitle();this.setupInfoSpace();this.drawLegend();(i="right"in this.ndata)?this.addAxes("left","right"):this.addAxes("all");this.drawBG();this.drawLogo();this.drawGuideline(0);this.lines=[];this.dots=this.r.set();d=typeof(a=this.opts.stacked)!=="undefined"&&a!==null?
this.stackedNdata:this.ndata;a=this.opts.area?Sai.AreaPlot:Sai.LinePlot;this.plotSets=this.r.set();this.plots=[];if(i){this.plots.push((new a(this.r,this.px,this.py,this.pw,this.ph,d.left)).render(this.colors,typeof(b=this.opts.lineWidth)!=="undefined"&&b!==null?this.opts.lineWidth:2,this.opts.stacked));this.plotSets.push(this.plots[0].set);this.plots.push((new a(this.r,this.px,this.py,this.pw,this.ph,d.right)).render(this.colors,typeof(c=this.opts.lineWidth)!=="undefined"&&c!==null?this.opts.lineWidth:
2,this.opts.stacked));this.plotSets.push(this.plots[1].set)}else{this.plots.push((new a(this.r,this.px,this.py,this.pw,this.ph,d.all)).render(this.colors,typeof(e=this.opts.lineWidth)!=="undefined"&&e!==null?this.opts.lineWidth:2,this.opts.stacked));this.plotSets.push(this.plots[0].set)}b=d.all;for(j in b)if(n.call(b,j))if(j!=="__YVALS__")this.dots.push(this.r.circle(0,0,4).attr({fill:typeof(f=this.colors==undefined?undefined:this.colors[j])!=="undefined"&&f!==null?this.colors==undefined?undefined:
this.colors[j]:"black"}).hide());this.r.set().push(this.bg,this.plotSets,this.dots,this.logo,this.guidelines).mousemove(q(function(h){var l,k,o,m,p,r,u,v,s,w;u=this.getIndex(h);v={};v[this.__LABELS__]=this.data[this.__LABELS__][u];h=d.all;for(j in h)if(n.call(h,j))if(typeof(l=this.data[j])!=="undefined"&&l!==null)v[j]=this.data[j][u];this.drawInfo(v);r=0;l=[];h=d.all;for(j in h)n.call(h,j)&&j!=="__YVALS__"&&l.push(function(){k=[];m=this.plots;o=0;for(p=m.length;o<p;o++){s=m[o];j in s.dndata&&k.push(function(){w=
s.dndata[j][u];typeof w!=="undefined"&&w!==null?this.dots[r].attr({cx:w[0],cy:w[1]}).show().toFront():this.dots[r].hide();return r++}.call(this))}return k}.call(this));return l},this)).mouseout(q(function(){this.drawInfo({},true);return this.dots.hide()},this));this.logo==undefined||this.logo.toFront();return this};Sai.Sparkline=function(){return Sai.Chart.apply(this,arguments)};g(Sai.Sparkline,Sai.Chart);Sai.Sparkline.prototype.dataGroups=function(){return{data:["data"]}};Sai.Sparkline.prototype.render=
function(){this.drawBG();this.plots=this.r.set();this.plots.push((new Sai.LinePlot(this.r,this.x,this.y,this.w,this.h,this.ndata.data)).render({data:this.colors&&this.colors[series]||"black"},1).set);return this};Sai.BarChart=function(){return Sai.Chart.apply(this,arguments)};g(Sai.BarChart,Sai.Chart);Sai.BarChart.prototype.getMin=function(){return 0};Sai.BarChart.prototype.groupsToNullPad=function(){var a,b,c;a=[];b=this.dataGroups();for(c in b)n.call(b,c)&&a.push(c);return a};Sai.BarChart.prototype.nonNegativeGroups=
function(){var a,b,c;a=[];b=this.dataGroups();for(c in b)n.call(b,c)&&a.push(c);return a};Sai.BarChart.prototype.render=function(){var a,b,c,e,f,d,i;this.drawTitle();this.setupInfoSpace();this.drawLegend();this.addAxes("all");this.drawLogo();this.drawBG();if("all"in this.ndata){this.guidelines=this.r.set();b=this.ndata.all.__YVALS__;a=0;for(c=b.length;a<c;a++){i=b[a];this.drawGuideline(i)}}this.plots=this.r.set();a={};c={};c[this.__LABELS__]=this.data[this.__LABELS__];b=typeof(e=this.opts.stacked)!==
"undefined"&&e!==null?this.stackedNdata:this.ndata;e=b.all;for(d in e)if(n.call(e,d))if(!(d.match("^__")||d===this.__LABELS__)){a[d]=b.all[d];c[d]=this.data[d]}this.plots.push((new Sai.BarPlot(this.r,this.px,this.py,this.pw,this.ph,a,c)).render(typeof(f=this.opts.stacked)!=="undefined"&&f!==null,this.colors,this.opts.interactive,this.drawInfo).set);this.logo==undefined||this.logo.toFront();return this};Sai.StockChart=function(){return Sai.Chart.apply(this,arguments)};g(Sai.StockChart,Sai.Chart);Sai.StockChart.prototype.groupsToNullPad=
function(){return["prices","volume","__META__"]};Sai.StockChart.prototype.dataGroups=function(a){var b,c;b={__META__:[this.__LABELS__]};if("volume"in this.data)b.volume=["volume"];for(c in a)if(n.call(a,c))if(this.caresAbout(c)&&!(this.__LABELS__===c||"volume"===c)){b.prices=typeof b.prices!=="undefined"&&b.prices!==null?b.prices:[];b.prices.push(c)}return b};Sai.StockChart.prototype.nonNegativeGroups=function(){return["volume"]};Sai.StockChart.prototype.render=function(){var a,b,c,e,f,d,i;if(!(typeof(a=
this.ndata.prices)!=="undefined"&&a!==null&&"open"in this.ndata.prices&&"close"in this.ndata.prices&&"high"in this.ndata.prices&&"low"in this.ndata.prices)){this.showError("This chart requires data series named 'open', 'close', 'high', and 'low'.\n \nOnce you add series with these names, the chart will display.");return null}this.drawTitle();this.setupInfoSpace();e={};b=false;a=this.ndata.prices;for(i in a)if(n.call(a,i))if(!("open"===i||"close"===i||"high"===i||"low"===i)&&!(i.match("^__")||i===
this.__LABELS__)){e[i]=(this.colors==undefined?undefined:this.colors[i])||"black";b=true}b&&this.drawLegend(e);this.colors=typeof this.colors!=="undefined"&&this.colors!==null?this.colors:{};this.colors.up=typeof this.colors.up!=="undefined"&&this.colors.up!==null?this.colors.up:"black";this.colors.down=typeof this.colors.down!=="undefined"&&this.colors.down!==null?this.colors.down:"red";this.colors.vol_up=typeof this.colors.vol_up!=="undefined"&&this.colors.vol_up!==null?this.colors.vol_up:"#666666";
this.colors.vol_down=typeof this.colors.vol_down!=="undefined"&&this.colors.vol_down!==null?this.colors.vol_down:"#cc6666";this.addAxes("prices");this.drawLogo();this.drawBG();this.drawGuideline(0,"prices");this.plots=this.r.set();e={up:[],down:[]};a={};b=this.ndata.prices;for(f in b)if(n.call(b,f))f.match("^__")||f===this.__LABELS__||(a[f]=this.data[f]);if(typeof(c=this.data.volume)!=="undefined"&&c!==null)a.vol=this.data.volume;if("volume"in this.ndata){c=this.ndata.volume.volume.length;for(f=0;0<=
c?f<c:f>c;0<=c?f+=1:f-=1)if(this.ndata.volume.volume[f]!==null)if(f&&this.ndata.prices.close[f-1]&&this.ndata.prices.close[f][1]<this.ndata.prices.close[f-1][1]){e.down.push(this.ndata.volume.volume[f]);e.up.push([this.ndata.volume.volume[f][0],0])}else{e.up.push(this.ndata.volume.volume[f]);e.down.push([this.ndata.volume.volume[f][0],0])}else{e.up.push([0,0]);e.down.push([0,0])}this.plots.push((new Sai.BarPlot(this.r,this.px,this.py,this.pw,this.ph*0.2,e,a)).render(true,{up:this.colors.vol_up,down:this.colors.vol_down}).set)}this.plots.push((new Sai.CandlestickPlot(this.r,
this.px,this.py,this.pw,this.ph,{open:this.ndata.prices.open,close:this.ndata.prices.close,high:this.ndata.prices.high,low:this.ndata.prices.low},a)).render(this.colors,Math.min(5,this.pw/this.ndata.prices.open.length-2)).set);f={};c=this.ndata.prices;for(i in c)if(n.call(c,i))"open"===i||"close"===i||"high"===i||"low"===i||i.match("^__")||i===this.__LABELS__||(f[i]=this.ndata.prices[i]);this.plots.push((new Sai.LinePlot(this.r,this.px,this.py,this.pw,this.ph,f)).render(this.colors).set);d=this.pw/
(this.data[this.__LABELS__].length-1);this.glow=this.r.rect(this.px-d/2,this.py-this.ph,d,this.ph).attr({fill:"0-"+this.opts.bgcolor+"-#DDAA99-"+this.opts.bgcolor,"stroke-width":0,"stroke-opacity":0}).toBack().hide();this.bg.toBack();this.r.set().push(this.bg,this.plots,this.logo,this.glow,this.guidelines).mousemove(q(function(j){var h,l,k,o,m;k=this.getIndex(j);o={};o[this.__LABELS__]=this.data[this.__LABELS__][k];m=false;j=this.ndata.prices;for(i in j)if(n.call(j,i))if(!(i.match("^__")||i===this.__LABELS__))if(typeof(h=
this.data[i]==undefined?undefined:this.data[i][k])!=="undefined"&&h!==null){o[i]=this.data[i][k];m=true}if(typeof(l=this.data.volume==undefined?undefined:this.data.volume[k])!=="undefined"&&l!==null){o.volume=this.data.volume[k];m=true}this.drawInfo(o);return m?this.glow.attr({x:this.px+d*(k-0.5)}).show():null},this)).mouseout(q(function(){this.drawInfo({},true);return this.glow.hide()},this));this.logo==undefined||this.logo.toFront();return this};Sai.GeoChart=function(){var a;a=this;this.renderPlot=
function(){return Sai.GeoChart.prototype.renderPlot.apply(a,arguments)};return Sai.Chart.apply(this,arguments)};g(Sai.GeoChart,Sai.Chart);Sai.GeoChart.prototype.plotType=Sai.GeoPlot;Sai.GeoChart.prototype.interactiveHistogram=true;Sai.GeoChart.prototype.getMax=function(a){return Math.max.apply(Math,a)};Sai.GeoChart.prototype.getMin=function(a){return Math.min.apply(Math,a)};Sai.GeoChart.prototype.normalize=function(a){var b,c,e,f,d,i,j,h,l,k,o,m,p;this.ndata={};this.bounds={};l={};k={};for(p in a)if(n.call(a,
p))if(!(p.match("^__")||p===this.__LABELS__))if(typeof(b=a[p])!=="undefined"&&b!==null){c=[];f=a[p];e=0;for(d=f.length;e<d;e++){h=f[e];typeof h!=="undefined"&&h!==null&&c.push(h)}c=c;l[p]=this.getMax(c,p);if(!(typeof o!=="undefined"&&o!==null)||l[p]>o)o=l[p];k[p]=this.getMin(c,p);if(!(typeof m!=="undefined"&&m!==null)||k[p]<m)m=k[p]}for(p in a)if(n.call(a,p))if(!(p.match("^__")||p===this.__LABELS__))if(typeof(i=a[p])!=="undefined"&&i!==null){if(this.opts.groupedNormalization){f=o;d=m}else{f=l[p];
d=k[p]}this.bounds[p]=[d,f];h=this.ndata;var r=p;b=[];c=a[p].length;for(e=0;0<=c?e<c:e>c;0<=c?e+=1:e-=1)b.push(typeof(j=a[p][e])!=="undefined"&&j!==null?[e/(a[p].length-1),(a[p][e]-d)/(f-d)]:null);h[r]=b}return[]};Sai.GeoChart.prototype.dataGroups=function(a){var b,c;b=[];for(c in a)if(n.call(a,c))if(c.match("^__")||c===this.__LABELS__)b.push(c);b={__META__:b};for(c in a)if(n.call(a,c))c.match("^__")||c===this.__LABELS__||(b[c]=[c]);return b};Sai.GeoChart.prototype.drawHistogramLegend=function(a){var b,
c,e,f,d,i,j,h,l,k,o,m,p,r;this.histogramLegend=this.r.set();l=Math.max(0.1*(this.h-this.padding.bottom-this.padding.top),50);p=Math.min(150,(this.w-this.padding.left-this.padding.right-20)/a.length);b=a.length;for(o=0;0<=b?o<b:o>b;0<=b?o+=1:o-=1){m=a[o];k=this.x+o*p;c=[];e=this.ndata[m].length;for(d=0;0<=e?d<e:d>e;0<=e?d+=1:d-=1)if(typeof(f=this.ndata[m][d])!=="undefined"&&f!==null)c.push(this.ndata[m][d][1]);c=c;if(typeof(i=this.bounds==undefined?undefined:this.bounds[m])!=="undefined"&&i!==null){d=
this.bounds[m];e=d[0];d=d[1]}else{e=[];j=this.data[m];d=0;for(h=j.length;d<h;d++){r=j[d];typeof r!=="undefined"&&r!==null&&e.push(r)}e=e;d=[Math.min.apply(Math,e),Math.max.apply(Math,e)];e=d[0];d=d[1]}d=this.getYAxisVals(e,d,true);e=d[0];d=d[d.length-1];this.histogramLegend.push(k=this.r.sai.prim.histogram(k,this.y-this.padding.bottom,p*0.8,l,c,e,d,m,this.colors[m],"white",this.opts.fromWhite));this.opts.interactive&&this.setupHistogramInteraction(k,m)}this.histogramLegend.translate((this.w-this.padding.left-
this.padding.right-this.histogramLegend.getBBox().width)/2,0);return this.padding.bottom+=l+5};Sai.GeoChart.prototype.setupHistogramInteraction=function(a,b){return a.click(q(function(){return this.renderPlot(b)},this)).hover(q(function(c){return q(function(){c.attr({"fill-opacity":0.75});return this.drawInfo({"Click to display on map":b})},this)},this)(a),q(function(c){return q(function(){c.attr({"fill-opacity":1});return this.drawInfo()},this)},this)(a))};Sai.GeoChart.prototype.renderPlot=function(a){this.geoPlot==
undefined||this.geoPlot.set.remove();this.geoPlot=(new this.plotType(this.r,this.px,this.py,this.pw,this.ph,this.ndata,this.data,{fromWhite:this.opts.fromWhite})).render(this.colors||{},this.data.__MAP__,this.__LABELS__,a,this.opts.bgcolor,this.opts.interactive,this.drawInfo);return this.logo==undefined?undefined:this.logo.toFront()};Sai.GeoChart.prototype.default_info=function(){return{"":this.opts.interactive?"Click histogram below to change map display":""}};Sai.GeoChart.prototype.render=function(){var a,
b,c;this.drawTitle();this.setupInfoSpace();this.drawHistogramLegend(function(){a=[];b=this.data;for(c in b)if(n.call(b,c))c.match("^__")||c===this.__LABELS__||a.push(c);return a}.call(this));this.setPlotCoords();this.drawLogo();this.drawBG();this.drawInfo();this.renderPlot(this.data.__DEFAULT__);return this};Sai.ChromaticGeoChart=function(){return Sai.GeoChart.apply(this,arguments)};g(Sai.ChromaticGeoChart,Sai.GeoChart);Sai.ChromaticGeoChart.prototype.plotType=Sai.ChromaticGeoPlot;Sai.ChromaticGeoChart.prototype.interactiveHistogram=
false;Sai.ChromaticGeoChart.prototype.default_info=function(){return{}};Sai.ChromaticGeoChart.prototype.setupHistogramInteraction=function(){return false}})();
